"""empty message

Revision ID: 5b0f0bbe0346
Revises: d8fdfaf91a3f
Create Date: 2021-11-30 16:02:33.009420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0f0bbe0346'
down_revision = 'd8fdfaf91a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uesrs',
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('user_medicine',
    sa.Column('user_target_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=32), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_target_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_medicine')
    op.drop_table('uesrs')
    # ### end Alembic commands ###
