"""empty message

Revision ID: 86b8bd9fc2bc
Revises: 
Create Date: 2021-11-30 13:39:33.935640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b8bd9fc2bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newtable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newtable',
    sa.Column('entpname', sa.VARCHAR(length=22), autoincrement=False, nullable=True),
    sa.Column('itemname', sa.VARCHAR(length=151), autoincrement=False, nullable=True),
    sa.Column('itemseq', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('efcyqesitm', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('usemethodqesitm', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('atpnwarnqesitm', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('atpnqesitm', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('intrcqesitm', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('seqesitm', sa.VARCHAR(length=981), autoincrement=False, nullable=True),
    sa.Column('depositmethodqesitm', sa.VARCHAR(length=157), autoincrement=False, nullable=True),
    sa.Column('opende', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updatede', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('itemimage', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
