"""empty message

Revision ID: d8fdfaf91a3f
Revises: 86b8bd9fc2bc
Create Date: 2021-11-30 13:45:09.732285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8fdfaf91a3f'
down_revision = '86b8bd9fc2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entpname', sa.String(length=22), nullable=True),
    sa.Column('itemname', sa.String(length=151), nullable=True),
    sa.Column('itemseq', sa.String(length=1000), nullable=True),
    sa.Column('efcyqesitm', sa.String(length=1000), nullable=True),
    sa.Column('usemethodqesitm', sa.String(length=1000), nullable=True),
    sa.Column('atpnwarnqesitm', sa.String(length=1000), nullable=True),
    sa.Column('atpnqesitm', sa.String(length=2000), nullable=True),
    sa.Column('intrcqesitm', sa.String(length=1000), nullable=True),
    sa.Column('seqesitm', sa.String(length=981), nullable=True),
    sa.Column('depositmethodqesitm', sa.String(length=157), nullable=True),
    sa.Column('opende', sa.Date(), nullable=True),
    sa.Column('updatede', sa.Date(), nullable=True),
    sa.Column('itemimage', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine')
    # ### end Alembic commands ###
